<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net6.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>todo.ico</ApplicationIcon>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="todo.ico" />
    <Resource Include="Resources\asterisk.png" />
    <Resource Include="Resources\error.png" />
    <Resource Include="Resources\exclamation.png" />
    <Resource Include="Resources\hand.png" />
    <Resource Include="Resources\information.png" />
    <Resource Include="Resources\none.png" />
    <Resource Include="Resources\question.png" />
    <Resource Include="Resources\stop.png" />
    <Resource Include="Resources\Warning.png" />
  </ItemGroup>
</Project>
